"""add_scheduled_at_to_messages

Revision ID: 018991b60b4d
Revises: eb885d3e9438
Create Date: 2026-01-24 21:22:23.540090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018991b60b4d'
down_revision: Union[str, Sequence[str], None] = 'eb885d3e9438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_messages_scheduled_at'), 'messages', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_scheduled_at'), table_name='messages')
    op.drop_column('messages', 'scheduled_at')
    # ### end Alembic commands ###
