"""add waba settings

Revision ID: 05a662d0264b
Revises: f1cbf7dab897
Create Date: 2026-01-17 12:17:04.409052

"""

from typing import Sequence, Union

import sqlalchemy as sa
import src.core.database
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05a662d0264b"
down_revision: Union[str, Sequence[str], None] = "f1cbf7dab897"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "waba_accounts",
        sa.Column("access_token", src.core.database.EncryptedString(), nullable=False),
    )
    op.add_column(
        "waba_accounts",
        sa.Column("app_secret", src.core.database.EncryptedString(), nullable=False),
    )
    op.add_column(
        "waba_accounts",
        sa.Column("verify_token", src.core.database.EncryptedString(), nullable=False),
    )
    op.add_column(
        "waba_accounts", sa.Column("graph_api_version", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("waba_accounts", "graph_api_version")
    op.drop_column("waba_accounts", "verify_token")
    op.drop_column("waba_accounts", "app_secret")
    op.drop_column("waba_accounts", "access_token")
    # ### end Alembic commands ###
