"""add custom_data

Revision ID: 15863af40fe3
Revises: b8d2b3a79b28
Create Date: 2026-01-22 17:08:22.098776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15863af40fe3'
down_revision: Union[str, Sequence[str], None] = 'b8d2b3a79b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_column('contacts', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'custom_data')
    # ### end Alembic commands ###
