"""remove complex scheduling fields

Revision ID: 592bdc816081
Revises: adb8e58238b4
Create Date: 2025-12-28 13:30:45.660488

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '592bdc816081'
down_revision: Union[str, Sequence[str], None] = 'adb8e58238b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_contacts', 'last_sent_at')
    op.drop_column('campaign_contacts', 'can_send_after')
    op.drop_column('campaigns', 'messages_per_second')
    op.drop_column('contacts', 'can_message_after')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('can_message_after', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('messages_per_second', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('campaign_contacts', sa.Column('can_send_after', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('campaign_contacts', sa.Column('last_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
