"""add is_session_active

Revision ID: 647f0c2ed439
Revises: 16c06fcee55c
Create Date: 2026-01-16 09:57:03.344433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '647f0c2ed439'
down_revision: Union[str, Sequence[str], None] = '16c06fcee55c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('last_incoming_message_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'last_incoming_message_at')
    # ### end Alembic commands ###
