"""init

Revision ID: 773f6d8e138b
Revises:
Create Date: 2026-01-17 16:19:47.024103

"""

from typing import Sequence, Union

import sqlalchemy as sa
import src.core.database
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "773f6d8e138b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("unread_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "OPTED_OUT", "BLOCKED", "ARCHIVED", name="contactstatus"),
            nullable=False,
        ),
        sa.Column("last_message_id", sa.Uuid(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_incoming_message_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["last_message_id"],
            ["messages.id"],
            name="fk_contacts_last_message_id",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
    )
    op.create_index(
        op.f("ix_contacts_phone_number"), "contacts", ["phone_number"], unique=True
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
    )
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.create_table(
        "waba_accounts",
        sa.Column("waba_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("access_token", src.core.database.EncryptedString(), nullable=False),
        sa.Column("app_secret", src.core.database.EncryptedString(), nullable=False),
        sa.Column("verify_token", src.core.database.EncryptedString(), nullable=False),
        sa.Column("graph_api_version", sa.String(), nullable=False),
        sa.Column("account_review_status", sa.String(), nullable=True),
        sa.Column("business_verification_status", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_waba_accounts")),
    )
    op.create_table(
        "webhook_logs",
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_logs")),
    )
    op.create_table(
        "contact_tags",
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_contact_tags_contact_id_contacts"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_contact_tags_tag_id_tags")
        ),
        sa.PrimaryKeyConstraint("contact_id", "tag_id", name=op.f("pk_contact_tags")),
    )
    op.create_table(
        "templates",
        sa.Column("waba_id", sa.Uuid(), nullable=False),
        sa.Column("meta_template_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column(
            "components", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["waba_id"],
            ["waba_accounts.id"],
            name=op.f("fk_templates_waba_id_waba_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_templates")),
    )
    op.create_index(
        op.f("ix_templates_meta_template_id"),
        "templates",
        ["meta_template_id"],
        unique=True,
    )
    op.create_index(op.f("ix_templates_name"), "templates", ["name"], unique=False)
    op.create_table(
        "waba_phone_numbers",
        sa.Column("waba_id", sa.Uuid(), nullable=False),
        sa.Column("phone_number_id", sa.String(), nullable=False),
        sa.Column("display_phone_number", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("quality_rating", sa.String(), nullable=False),
        sa.Column("messaging_limit_tier", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["waba_id"],
            ["waba_accounts.id"],
            name=op.f("fk_waba_phone_numbers_waba_id_waba_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_waba_phone_numbers")),
    )
    op.create_index(
        op.f("ix_waba_phone_numbers_phone_number_id"),
        "waba_phone_numbers",
        ["phone_number_id"],
        unique=True,
    )
    op.create_table(
        "campaigns",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SCHEDULED",
                "RUNNING",
                "PAUSED",
                "COMPLETED",
                "FAILED",
                name="campaignstatus",
            ),
            nullable=False,
        ),
        sa.Column("message_type", sa.String(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("message_body", sa.String(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_contacts", sa.Integer(), nullable=False),
        sa.Column("sent_count", sa.Integer(), nullable=False),
        sa.Column("delivered_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("read_count", sa.Integer(), nullable=False),
        sa.Column("replied_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
            name=op.f("fk_campaigns_template_id_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
    )
    op.create_index(op.f("ix_campaigns_status"), "campaigns", ["status"], unique=False)
    op.create_table(
        "messages",
        sa.Column("wamid", sa.String(), nullable=True),
        sa.Column("waba_phone_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("INBOUND", "OUTBOUND", name="messagedirection"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENT",
                "DELIVERED",
                "READ",
                "FAILED",
                "RECEIVED",
                name="messagestatus",
            ),
            nullable=False,
        ),
        sa.Column("message_type", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column("reply_to_message_id", sa.Uuid(), nullable=True),
        sa.Column("reaction", sa.String(), nullable=True),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_messages_contact_id_contacts"),
        ),
        sa.ForeignKeyConstraint(
            ["reply_to_message_id"],
            ["messages.id"],
            name=op.f("fk_messages_reply_to_message_id_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
            name=op.f("fk_messages_template_id_templates"),
        ),
        sa.ForeignKeyConstraint(
            ["waba_phone_id"],
            ["waba_phone_numbers.id"],
            name=op.f("fk_messages_waba_phone_id_waba_phone_numbers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(op.f("ix_messages_wamid"), "messages", ["wamid"], unique=False)
    op.create_table(
        "campaign_contacts",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "SENT",
                "DELIVERED",
                "READ",
                "FAILED",
                "REPLIED",
                name="campaigndeliverystatus",
            ),
            nullable=False,
        ),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_contacts_campaign_id_campaigns"),
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_campaign_contacts_contact_id_contacts"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_campaign_contacts_message_id_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_contacts")),
    )
    op.create_index(
        op.f("ix_campaign_contacts_campaign_id"),
        "campaign_contacts",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_contacts_contact_id"),
        "campaign_contacts",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_contacts_status"),
        "campaign_contacts",
        ["status"],
        unique=False,
    )
    op.create_table(
        "media_files",
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("meta_media_id", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_mime_type", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("caption", sa.String(), nullable=True),
        sa.Column("r2_key", sa.String(), nullable=False),
        sa.Column("bucket_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_media_files_message_id_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_files")),
    )
    op.create_index(
        op.f("ix_media_files_meta_media_id"),
        "media_files",
        ["meta_media_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_files_meta_media_id"), table_name="media_files")
    op.drop_table("media_files")
    op.drop_index(op.f("ix_campaign_contacts_status"), table_name="campaign_contacts")
    op.drop_index(
        op.f("ix_campaign_contacts_contact_id"), table_name="campaign_contacts"
    )
    op.drop_index(
        op.f("ix_campaign_contacts_campaign_id"), table_name="campaign_contacts"
    )
    op.drop_table("campaign_contacts")
    op.drop_index(op.f("ix_messages_wamid"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_campaigns_status"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(
        op.f("ix_waba_phone_numbers_phone_number_id"), table_name="waba_phone_numbers"
    )
    op.drop_table("waba_phone_numbers")
    op.drop_index(op.f("ix_templates_name"), table_name="templates")
    op.drop_index(op.f("ix_templates_meta_template_id"), table_name="templates")
    op.drop_table("templates")
    op.drop_table("contact_tags")
    op.drop_table("webhook_logs")
    op.drop_table("waba_accounts")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_contacts_phone_number"), table_name="contacts")
    op.drop_table("contacts")
    # ### end Alembic commands ###
