"""remove_campaign_statistics_and_contact_status

Revision ID: 80a8cc839607
Revises: 5875fe64f491
Create Date: 2026-01-27 10:56:00.027529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80a8cc839607'
down_revision: Union[str, Sequence[str], None] = '5875fe64f491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_contacts_status'), table_name='campaign_contacts')
    op.drop_column('campaign_contacts', 'status')
    op.drop_column('campaigns', 'delivered_count')
    op.drop_column('campaigns', 'total_contacts')
    op.drop_column('campaigns', 'failed_count')
    op.drop_column('campaigns', 'sent_count')
    op.drop_column('campaigns', 'message_body')
    op.drop_column('campaigns', 'read_count')
    op.drop_column('campaigns', 'message_type')
    op.drop_column('campaigns', 'replied_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('replied_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('message_type', sa.VARCHAR(), server_default=sa.text("'template'::character varying"), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('read_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('message_body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('sent_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('failed_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('total_contacts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('delivered_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('campaign_contacts', sa.Column('status', postgresql.ENUM('QUEUED', 'SENT', 'DELIVERED', 'READ', 'FAILED', 'REPLIED', name='campaigndeliverystatus'), server_default=sa.text("'QUEUED'::campaigndeliverystatus"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_campaign_contacts_status'), 'campaign_contacts', ['status'], unique=False)
    # ### end Alembic commands ###
