"""add is_replied to campaign_contact

Revision ID: 88b151206c14
Revises: 80a8cc839607
Create Date: 2026-01-27 14:42:21.775244

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88b151206c14"
down_revision: Union[str, Sequence[str], None] = "80a8cc839607"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaign_contacts",
        sa.Column(
            "is_replied", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaign_contacts", "is_replied")
    # ### end Alembic commands ###
