"""add last message

Revision ID: 8f00452c7178
Revises: 592bdc816081
Create Date: 2026-01-04 13:21:26.117159

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f00452c7178'
down_revision: Union[str, Sequence[str], None] = '592bdc816081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('last_message_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'messages', ['last_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'last_message_id')
    # ### end Alembic commands ###
