"""Make message body optional

Revision ID: ac662ce09412
Revises: 
Create Date: 2025-12-24 10:52:00.258240

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac662ce09412'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_phone_number'), 'contacts', ['phone_number'], unique=True)
    op.create_table('waba_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('waba_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_review_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_verification_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('waba_id', sa.Uuid(), nullable=False),
    sa.Column('meta_template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['waba_id'], ['waba_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_meta_template_id'), 'templates', ['meta_template_id'], unique=True)
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=False)
    op.create_table('waba_phone_numbers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('waba_id', sa.Uuid(), nullable=False),
    sa.Column('phone_number_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quality_rating', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('messaging_limit_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['waba_id'], ['waba_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waba_phone_numbers_phone_number_id'), 'waba_phone_numbers', ['phone_number_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wamid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('waba_phone_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED', 'RECEIVED', name='messagestatus'), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['waba_phone_id'], ['waba_phone_numbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_wamid'), 'messages', ['wamid'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('meta_media_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('r2_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bucket_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_meta_media_id'), 'media_files', ['meta_media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_files_meta_media_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_messages_wamid'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_waba_phone_numbers_phone_number_id'), table_name='waba_phone_numbers')
    op.drop_table('waba_phone_numbers')
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.drop_index(op.f('ix_templates_meta_template_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_table('webhook_logs')
    op.drop_table('waba_accounts')
    op.drop_index(op.f('ix_contacts_phone_number'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
