"""add unread_count to contacts

Revision ID: bf20c29ecdc5
Revises: ac662ce09412
Create Date: 2025-12-25 11:08:57.755737

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf20c29ecdc5"
down_revision: Union[str, Sequence[str], None] = "ac662ce09412"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column("unread_count", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "unread_count")
    # ### end Alembic commands ###
