"""add unread_count to contacts

Revision ID: c60ffcf04692
Revises: bf20c29ecdc5
Create Date: 2025-12-25 21:01:47.171605

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c60ffcf04692"
down_revision: Union[str, Sequence[str], None] = "bf20c29ecdc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SCHEDULED",
                "RUNNING",
                "PAUSED",
                "COMPLETED",
                "FAILED",
                name="campaignstatus",
            ),
            nullable=False,
        ),
        sa.Column("message_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("message_body", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("total_contacts", sa.Integer(), nullable=False),
        sa.Column("sent_count", sa.Integer(), nullable=False),
        sa.Column("delivered_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("messages_per_second", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "campaign_contacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "SCHEDULED",
                "SENT",
                "DELIVERED",
                "READ",
                "FAILED",
                "OPTED_OUT",
                "BLOCKED",
                name="contactstatus",
            ),
            nullable=False,
        ),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("last_sent_at", sa.DateTime(), nullable=True),
        sa.Column("can_send_after", sa.DateTime(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "contacts",
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "SCHEDULED",
                "SENT",
                "DELIVERED",
                "READ",
                "FAILED",
                "OPTED_OUT",
                "BLOCKED",
                name="contactstatus",
            ),
            nullable=False,
            server_default="NEW",
        ),
    )
    op.add_column(
        "contacts", sa.Column("last_message_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "contacts", sa.Column("can_message_after", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "contacts",
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "contacts",
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "tags")
    op.drop_column("contacts", "source")
    op.drop_column("contacts", "can_message_after")
    op.drop_column("contacts", "last_message_at")
    op.drop_column("contacts", "status")
    op.drop_table("campaign_contacts")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
