"""add waba_phone_id to campaigns

Revision ID: f79c8da494da
Revises: 773f6d8e138b
Create Date: 2026-01-19 09:51:07.885120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79c8da494da'
down_revision: Union[str, Sequence[str], None] = '773f6d8e138b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('waba_phone_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_campaigns_waba_phone_id_waba_phone_numbers'), 'campaigns', 'waba_phone_numbers', ['waba_phone_id'], ['id'])
    op.create_foreign_key('fk_contacts_last_message_id', 'contacts', 'messages', ['last_message_id'], ['id'], use_alter=True)
    op.alter_column('messages', 'waba_phone_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'waba_phone_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('fk_contacts_last_message_id', 'contacts', type_='foreignkey')
    op.drop_constraint(op.f('fk_campaigns_waba_phone_id_waba_phone_numbers'), 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'waba_phone_id')
    # ### end Alembic commands ###
